### ISSUE TITLE
Suggestion: New custom name of fork

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#29]
сейчас при запуске FAR2L
выдаётся:
FAR2L, version 2.4.0-d8649393-beta Linux x86_64
Copyright (C) 1996-2000 Eugene Roshal, Copyright (C) 2000-2016 Far Group, Copyright (C) 2016-2023 Far People

рано или поздно надо как то показывать что это мод

например FAR2L-Lua хотя бы...

**Comment by shmuz** [comment]
Да, название надо поменять.
Не будет путаницы, не надо будет каждый раз употреблять слово "форк".
А также запускаться будут с разными именами и хранить конфигурации в разных местах.
Вот выбрать имя - это проблема.

**Comment by shmuz** [comment]
Проект переименован в far2m.
Соответственно изменился адрес: https://github.com/shmuz/far2m

**Comment by shmuz** [comment]
Done in b3f02220756f7bc2d5afdbc832df9b7edc54f8df.
