### ISSUE TITLE
Поломалась поддержка создания rar архивов

### ISSUE THREAD

**Issue by DM-VLK** [shmuz/far2m#30]
В последнее время заметил при сборке сообщение `rar archives support disabled due to UNRAR=.`,  после чего из MultiArc пропала возможность создавать rar архивы и его нет в списке архивов в конфигураторе плагина. Rar и unrar конечно есть. Собрал для теста свежий far2l-elfmz и там такой проблемы нет и rar архивы создаються.

**Comment by shmuz** [comment]
Как я уже говорил, оригинальные (не мои) плагины я не трогаю, а беру как есть.
Недавно я их обновил из репозитория elfmz, после чего видно это и произошло.
Но раз вы говорите, что у него работает - буду разбираться.

**Comment by shmuz** [comment]
@DM-VLK 
Проект переименован в far2m.
Соответственно изменился адрес: https://github.com/shmuz/far2m
