### ISSUE TITLE
Асинхронный режим работы макроса

### ISSUE THREAD

**Issue by johnd0e** [shmuz/far2m#36]
..при котором бы он не ждал окончания фаровской операции (типа копирования, подсчёта размера, построения дерева), которая была запущена клавишей из `Keys`.

*Проблема*: макродвижок по умолчанию "нажимает клавиши" синхронно: очередное нажатие возвращает управление после завершения операции, вызванной этим нажатием.
Поэтому текущая реализация предусматривает запрет обработки клавиатуры в процессе операции, что приводит к невозможности прервать (затянувшуюся) операцию штатным образом (Esc/CtrlBreak).

*Потенциальное решение*: предусмотреть возможность как-то явно указать, для определённых случаев, что синхронность не нужна. Например `mf.mode(3)` и/или `Keys("EnAsync/NoWait",...)`.

Источник: https://bugs.farmanager.com/view.php?id=2692

**Comment by shmuz** [comment]
Спасибо,
не подумайте, что выпендриваюсь, просто эта репозитория - то место, где я в основном нахожусь, и где шанс на какие-то мои действия выше.

**Comment by johnd0e** [comment]
> не подумайте, что выпендриваюсь

И в мыслях не было

**Comment by shmuz** [comment]
> Потенциальное решение: предусмотреть возможность как-то явно указать, для определённых случаев, что синхронность не нужна. Например mf.mode(3) и/или Keys("EnAsync/NoWait",...).

Желательно конкретный случай рассмотреть.
1. Макрос копирования (очень большого, для наглядности) файла: `lua: Keys("F5 Enter")`
    Прервать копирование не получится, и даже окошко копирования на экране не появится.
2. `lua: Keys("F5 EnOut Enter")` - здесь всё нормально.

**Comment by johnd0e** [comment]
> Желательно конкретный случай рассмотреть.

Подсчёт размера директории - F3 или CtrlQ.
Другие действительно решаются EnOut

**Comment by shmuz** [comment]
Сейчас я как раз играюсь с кодом, пробую разные варианты.

**Comment by shmuz** [comment]
Можно проверять `F3` и `CtrlQ` :)

**Comment by johnd0e** [comment]
https://github.com/FarGroup/FarManager/pull/706

**Comment by johnd0e** [comment]
Я вижу что прерывание работает даже без Keys"EnOut".
Значит стоит использовать тот же подход и в других местах?

**Comment by shmuz** [comment]
Да, только нужно будет немного поглубже разобраться.

По поводу возможности прерывать сканирование директорий мышью, далеко не уверен, что это правильно.

**Comment by shmuz** [comment]
Что-то ещё есть или можно закрывать?

**Comment by johnd0e** [comment]
Если в этом направлении более ничего пока не планируется, то да.

**Comment by shmuz** [comment]
OK.
Если появятся новые идеи или данные, всегда можно будет переоткрыть или открыть новый.
