### ISSUE TITLE
не работает буфер обмена в последующих запущенных экземплярах фара

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#38]
Ubuntu 23.04, SSH

В последующих запущенных экземплярах фара
не работает буфер обмена
те ctrlc/shiftins/ctrlv...

при попытке активации как бы подвисает ввод/вывод
нужно жать ESC чтобы отвисло

Far2L норм работает
может надо какой то код утянуть оттуда?

ps. FAR2L может ещё запросить в другом экзепмляре FAR2L текст диалог:
Please choose how this terminal application may use clipboard

пока не понял когда это может возникнуть, в FAR2M есть обработка этого?

**Comment by shmuz** [comment]
Telegram conversation:
> У меня буфер обмена (и твой макрос) работают, даже если far2m вызван 3 раза один из другого. Пробовал как с WX, так и с TTY.
