### ISSUE TITLE
crumbling far2l interface - same bug in far2l and far2m

### ISSUE THREAD

**Issue by sxored** [shmuz/far2m#41]
hello !

this bug is reproduced in fresh builds of elfmz/far2l and shmuz/far2m

for details and some screenshots see original issue in far2l repo

https://github.com/elfmz/far2l/issues/1342

some info

> screen and tmux in terminal (far2l TTY) has the same bug as freebsd https://github.com/elfmz/far2l/issues/929 and linux https://github.com/elfmz/far2l/issues/925
>
> I builded far2l leaving only
>
> support_esc_b = false
>
> and this bug disappeared.
>

**Comment by shmuz** [comment]
Please check the current master (as I borrowed the fix for elfmz#1804 from far2l).

**Comment by shmuz** [comment]
Closed due to no feedback.

**Comment by sxored** [comment]
thanks for the fixing issue with "screen" !
