### ISSUE TITLE
Неверная работа панели команд с Alt и мышью.

### ISSUE THREAD

**Issue by Release** [shmuz/far2m#46]
Если зажать клавишу Alt и нажать мышью на первую или вторую команду в панели команд внизу окна, то вместо открытия окна перехода открываются либо справка, либо главное меню.
В тоже время если нажать на третью команду "Просмотр", открывается окно просмотра текущего файла, т.е. команда срабатывает как и должна.

**Comment by Release** [comment]
Значит, у вас было другое поведение и скорее к описанной мной проблеме оно не имеет отношения. Но спасибо, что попытались помочь.

**Comment by Release** [comment]
Согласен, что скорее всего причина в каких-то настройках KDE Plasma, но у меня 99% настроек по умолчанию, а значит скорее всего проблема будет воспроизводится на всех системах с этой оболочкой. Потому я и предложил отслеживать нажатие/удержание по отдельности (через флаг), а не во время клика мышью (хотя бы как альтернативный метод работы).

**Comment by Release** [comment]
Еще один момент определенный в ходе тестирования. Если зажать Alt и понажимать мышью на другие файлы в той же панели, то надписи команд остаются как и должны, но если кликнуть на соседнюю панель, то надписи восстанавливаются как-будто клавишу Alt отпустили.

**Comment by shmuz** [comment]
Возможно получится выкроить время и поставить систему с KDE Plasma (а какая у вас ОС ?)

**Comment by Release** [comment]
Операционная система: Manjaro Linux 
Версия KDE Plasma: 5.27.9
Версия KDE Frameworks: 5.112.0
Версия Qt: 5.15.11
Версия ядра: 6.1.64-1-MANJARO (64-бита)
Графическая платформа: X11

**Comment by shmuz** [comment]
Хорошо, возможно получится попробовать на виртуалке, но это может занять определённое время.

**Comment by Release** [comment]
Ну, меня уже радует, что вы не отмахнулись от проблемы, а сроки не так важны - это же не оплачиваемая работа, а ваша добровольная деятельность.

**Comment by shmuz** [comment]
Естественно при получении новых данных отпишусь.

**Comment by shmuz** [comment]
Поставил новейшую Manjaro KDE Plasma. Проблема воспроизводится, именно как вы её описали.

Решение нашёл (по крайней мере у меня оно помогло).
Settings ->System settings ->  Hardware -> Input devices -> Keyboard -> Layouts -> Shortcuts for switching layouts -> Main shortcuts
**Снимите отметку с Alt+Shift и поставьте на Alt+Space.**

**Comment by shmuz** [comment]
Та проблема, что вы описали, это лишь верхушка айсберга.
Если раскладки настроены на переключение через Alt+Shift, то в Фар никакие комбинации с Alt+Shift не приходят правильно.

**Comment by shmuz** [comment]
1. В ОС или в оболочке проблема - мне нет разницы, мне важно в Фаре или нет.
2. Насчёт Ctrl+Alt+F - у меня работает корректно на этой системе (Plasma). Первое нажатие включает фильтр (в заголовке меню появляется `[]`, последующее (неважно после отпускания или без него) фильтр отключает.
3. Этот тикет закрываю, если будут ещё проблемы, открывайте новый.

**Comment by Release** [comment]
Имхо, если подобных проблем нет в других приложениях, как например "Visual Studio Code" или "Kate", то это проблема Фара. Но, "на нет и суда нет".
