### ISSUE TITLE
far:config, far:about

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#47]
Добавить функционал 
far:config
far:about

из кодовой базы Far2l

**Comment by akruphi** [comment]
Наверное не так-то просто просто будет перетянуть. Сейчас far: используют ряд не перетянутых из far2l фич, основные из которых:
* недавняя разбивка far2l/src/cfg/ConfigSaveLoad.cpp / ConfigSaveLoad.hpp на отдельные сущности ConfigOpt.cpp / ConfigOpt.hpp и ConfigOptEdit.cpp / ConfigOptEdit.hpp
* `ExMessager` из far2l/src/message.cpp / message.hpp (добавлен в сентябре)
* расширения far2l/src/vmenu.cpp / vmenu.hpp для строк заголовков и подсвечиваемых отдельным цветом префиксы заданного числа символов `PrefixLen` (из летнего кода показа в списках истории дат и времени).

и какие-то ещё мелочи elfmz рефакторил после мерженья навесок far:

**Comment by shmuz** [comment]
Скорее всего перетягивать не буду, но не потому что это не просто.
Некоторые вещи вижу по-другому, нельзя всё механически перетягивать.
Для far:config, мне кажется, нужен приличный рефакторинг сначала.
far:about я не уверен вообще, что он нужен.

Кстати, есть маленький дефект в реализации этих команд в far2l - если после двоеточия есть пробелы, команды не распознаются.

**Comment by akruphi** [comment]
> Кстати, есть маленький дефект в реализации этих команд в far2l - если после двоеточия есть пробелы, команды не распознаются.

Вроде и в виндовском far3 команды `far:about` и `far:config` не допускают пробел после `far:` или в совсем новых версиях добавили такую возможность?

**Comment by shmuz** [comment]
Да, я ознакомился с вашей реализацией (как пользователь). Заметьте, что я её не критикую.

> Вроде и в виндовском far3 команды far:about и far:config не допускают пробел после far:

Сейчас проверил и был удивлён, что это так.
Я рассматриваю `far:` как сущность, аналогичную вызову плагина по префиксу. Для плагинов считается хорошим тоном игнорировать начальные и конечные пробелы в команде, по крайней мере стандартные плагины для Far3 это делают.

**Comment by shmuz** [comment]
> > Для far:config, мне кажется, нужен приличный рефакторинг сначала.

> Ну пока вставлена в текущую структуру и работает. Буду признателен за любые пожелания и замечания.

Я имел в виду рефакторинг в far2m, а не в far2l.

**Comment by shmuz** [comment]
Пока ещё очень сырое, но уже работает.

![image](https://github.com/shmuz/far2m/assets/344558/a842914b-3e81-4d06-b895-ad1da336664c)

**Comment by Zeroes1** [comment]
1) А как посмотреть?
far:config
far:config: command not found

FAR2M, version 2.5.0-4a50da5-beta Linux x86_64

2) я тоже голосую за надобность far:about чуть что :)

**Comment by shmuz** [comment]
На данный момент посмотреть можно так:
1. Зайти в папку `luamacro/plug` и выполнить команду `lua:@./far_config.lua`
2. Но оно ещё не закончено

**Comment by shmuz** [comment]
@Zeroes1 , есть уже более новая версия, близкая к окончательной.
Жду отзывов и замечаний.

**Comment by Guest007** [comment]
>     1. Зайти в папку `luamacro/src` и выполнить команду `lua:@./far_config.lua`
Что-то такого файла там не вижу :-(
Куда смотерть?

**Comment by shmuz** [comment]
Это было временное расположение на период разработки.
Сейчас вызывается с командной строки `lm:farconfig`

**Comment by Zeroes1** [comment]
@Guest007 у меня  настроен вызов через меню F2 причём сразу с включённым поисковым фильтром

lua: mf.postmacro(Keys, "CtrlAltF") require("far2.far_config") ()

**Comment by Zeroes1** [comment]
теперь и lm:farabout реализована, закрываю.

**Comment by shmuz** [comment]
@Zeroes1 
ОК, я надеюсь его ещё улучшать в дальнейшем.
