### ISSUE TITLE
func goto: improvement

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#50]
Добавить "понимание" командой goto: путей содержащих обратные слеши

например есть файл с пробелом "custom.ini.man 2.txt"
CtrF на в FAR'e (linux) скидывает в ком строку путь в таком виде: 
/home/admin/Dindikov-Home/Import/f/Plugins/multiarc/plug/custom.ini.man\ 2.txt 

сделали CtrlC (те скопировали в буфер обмена)
на второй панели
goto:  +Shift Ins

goto: /home/admin/Dindikov-Home/Import/f/Plugins/multiarc/plug/custom.ini.man\ 2.txt 
сейчас произойдёт переход в каталог /home/admin/Dindikov-Home/Import/f/Plugins/multiarc/plug/ 
без позиционирования на файл

а если пути были с пробелами, то никуда переход не происходит вообще
пример пути:
/home/admin/Dindikov-Home/Import/f/Plugins/1\ 2\ 3/custom.ini.man.txt

**Comment by shmuz** [comment]
Пробуйте теперь.

**Comment by Zeroes1** [comment]
теперь всё OK, thanks!
