### ISSUE TITLE
Numeric Keys are not working in Far Editor

### ISSUE THREAD

**Issue by Golyshkin** [shmuz/far2m#51]
**Test Case:**

1. Set keyboard NumLock to ENABLE
2. Open Far editor for any file
3. Press Alt+F8 for open "Go To Position" modal window
4. Press any number on NumLock keyboard

**Actual Result:**
1. There is no any number is entered.

**Expected Result:**
1. Entered number should be displayed in "Go To Position" input field.

![image](https://github.com/shmuz/far2m/assets/772340/dd8a90df-5ef8-49d2-83ca-e346fb0fcd3c)

**Comment by shmuz** [comment]
Mint 21.2 and Ubuntu 23.10 - not reproduced.
The numbers appear in the input box.

**Comment by Zeroes1** [comment]
@Golyshkin может быть вы имеете блокирующие макросы?
в других местах как с вводом с цифрового блока?

ps. у меня тоже всё Ok.

**Comment by Golyshkin** [comment]
Как проверить такие макросы? Раньше не было, началось после того как накатил HEAD. На тек. момент у меня только вот это в виде макросов:

AltScreens.lua
AltX.lua
Panel.BS.lua
Panel.Del.lua
Panel.Esc.lua
Panel.SpaceToSelect.lua

Отключил их - не помогло :-(

**Comment by shmuz** [comment]
1. Вызовите из редактора по AltF8 диалог Go to.
2. Нвжмите `Ctrl.Ctrl.` (контрол-точка дважды)
3. Поверх диалога Go to должен появиться лругой диалог Define macro
4. Нажимайте разные цифры на нумпаде и расскажите, что при этом появляется (или не появляется) в поле ввода диалога Define macro,

**Comment by shmuz** [comment]
Закрываю, если появятся новые данные, можно переоткрыть.

**Comment by Golyshkin** [comment]
> Закрываю, если появятся новые данные, можно переоткрыть.

Думю, что надо понять почему это происходит именно с FAR. 

Если я вызываю его из терминала как ниже то бага не воспроизводится:

`$ GDK_BACKEND=x11 far2m`

Но при этом начинает воспроизводиться бага https://github.com/shmuz/far2m/issues/49 которую тоже закрыли. Что будем делать? Есть мысли как настроить правильно Wayland ENV для FAR2M?

**Comment by shmuz** [comment]
Ага, ну вот и новые данные появились - впервые прозвучало слово Wayland :)

**Comment by Golyshkin** [comment]
> Ага, ну вот и новые данные появились - впервые прозвучало слово Wayland :)

Да, теперь точно понятно что это все связано с Wayland, копаю тоже в эту сторону, но пока не понимаю как пофиксить...

**Comment by Golyshkin** [comment]
> Поигрался дополнительно.
> 
>     1. Обновил свой Mint до 21.3, там есть экспериментальная поддержка Wayland (можно выбрать во время логина). Пропал русский язык и иконка  индикации языка. Попытка установить заново не удалась. Видимо поддержка Wayland в Mint 21.3 уж слишком "экспериментальная". Тем не менее проблем с quick search и AltF8 в редакторе не заметил.
> 
>     2. Переключился на Ubuntu 23.10 - там с языками всё в порядке и `XDG_SESSION_TYPE=wayland`.
>        Но как я уже сообщал ранее, ни одна из этих 2-х проблем не повторяется.
>        Я полностью верю, что эти проблемы у вас наблюдаются, но интуиция подсказывает мне, что в Ubuntu 22.04 поддержка Wayland ещё была недостаточной. Если у вас есть опция перейти на Ubuntu 23.10, это было бы неплохо (я понимаю, что могут быть причины, не позволяющие обновиться).

попробуйте под UBUNTU

$ GDK_BACKEND=wayland far2m

**Comment by shmuz** [comment]
Увы, это ничего не изменило в плане обеих обсуждаемых проблем. Они не воспроизводятся.

**Comment by Golyshkin** [comment]
> Увы, это ничего не изменило в плане обеих обсуждаемых проблем. Они не воспроизводятся.

Может попробовать докер собрать для 21.3 мне? Уж не знаю даже что сказать... Не думаю что проблема прямо вот в 22.04, конечно....

**Comment by shmuz** [comment]
> Не думаю что проблема прямо вот в 22.04, конечно....

Вы правы. Я поставил сейчас Ubuntu 22.04, установил все необходимые пакеты, собрал far2m - ни одна из ваших двух проблем не воспроизводится.

**Comment by shmuz** [comment]
> Куда копать дальше?

Разобраться, какие факторы вызывают данное поведение.

У меня нет времени играться на своих системах, в очередной раз наблюдая, что неисправности не воспроизводятся. У вас есть система, где они проявляются, на ней и надо искать. Например: поставить ещё одну Ubuntu 22.04 и, сравнивая её поведение со своей системой, постепенно докопаться до влияющих факторов.

**Comment by Golyshkin** [comment]
> > Куда копать дальше?
> 
> Разобраться, какие факторы вызывают данное поведение.
> 
> У меня нет времени играться на своих системах, в очередной раз наблюдая, что неисправности не воспроизводятся. У вас есть система, где они проявляются, на ней и надо искать. Например: поставить ещё одну Ubuntu 22.04 и, сравнивая её поведение со своей системой, постепенно докопаться до влияющих факторов.

Понял, спасибо, буду наблюдать, если что проапдйчу тикеты...

**Comment by shmuz** [comment]
Сегодня я повторил то, что описано у вас в первом сообщении (на Ubuntu 22.04).
Стыдно признаться, но скорее всего, в своих предыдущих опытах, я что-то делал не так.
Сейчас всё полностью воспроизвелось, независимо от состояния NumLock, нумпад **не позволяет вводить цифры**.

В то же время, на Ubuntu 23.10 нумпад работает правильно, как и положено - в зависимости от состояния NumLock.

В обеих сегодняшних проверках я не менял никакие переменные окружения.

**Comment by shmuz** [comment]
Поскольку на Ubuntu 22.04 если звпускать far2m с ключом `--tty` нумпад работает, то подозрение на установленную библиотеку wxWidgets. У неё разные версии в Ubuntu 22.04 и Ubuntu 23.10

Ubuntu 22.04: libwxgtk-3.0-gtk3-dev
![image](https://github.com/shmuz/far2m/assets/344558/ccd20193-cc26-4325-a934-ec9b5c65ee5c)

Ubuntu 23.10: libwxgtk-3.2-dev
![image](https://github.com/shmuz/far2m/assets/344558/01d48ad4-fd45-41d0-9707-9a1f20323e35)

**Comment by Golyshkin** [comment]
Спасибо, новая библиотека не совместима с `Ubuntu 22.04.4 LTS`?

**Comment by shmuz** [comment]
> новая библиотека не совместима с Ubuntu 22.04.4 LTS?

Спросил у гугла, нашёл [вот эту](https://answers.launchpad.net/ubuntu/+question/707498) страницу. Там во 2-м ответе сверху вроде говорится, что это возможно.

**Comment by shmuz** [comment]
Обновил wxWidgets до версии 3.2, и проблема ушла.
```
sudo add-apt-repository ppa:hrzhu/wxwidgets3.2-backport
sudo apt update
sudo apt install libwxgtk3.2-dev
```
После этого закрыл фар и открыл терминал:
```
cd ~/far2m/_build && cmake ..
make
```
После этого всё заработало.

**Comment by shmuz** [comment]
Поскольку проблема не в фаре, закрываю.

**Comment by Golyshkin** [comment]
Вылечил через

![image](https://github.com/user-attachments/assets/c4a92f58-0e10-4e53-916e-7fef976f6960)

Видимо, новая библиотека тоже как-то прогрессивно повлияла на это anti-alias mode

**Comment by shmuz** [comment]
Да, у меня [ ] Disable antialiasing тоже выключен.
Рад, что у вас починилось.

**Comment by Golyshkin** [comment]
> Рад, что у вас починилось.

Спасибо Вам за работу! Вы делаете очень хороший продукт под Linux, я пользуюсь FAR уже 25 лет назад и очень рад что помогаю делать его лучше своим скромным вкладом в общее дело!

**Comment by shmuz** [comment]
Спасибо.
Мне только жаль, что вы (и некоторые другие пользователи far2m) не используете дополнительные плагины и макросы, находящиеся [здесь](https://github.com/shmuz/luafar2m). Они добавляют много интересных возможностей.
Безусловно, речь не идёт о том, чтобы поставить всё скопом, а о том, чтобы пробовать и отбирать для себя подходящие плагины и макросы.

**Comment by Golyshkin** [comment]
> Спасибо. Мне только жаль, что вы (и некоторые другие пользователи far2m) не используете дополнительные плагины и макросы, находящиеся [здесь](https://github.com/shmuz/luafar2m). Они добавляют много интересных возможностей. Безусловно, речь не идёт о том, чтобы поставить всё скопом, а о том, чтобы пробовать и отбирать для себя подходящие плагины и макросы.

Почему, я активно использую вот эти макросы

```
AltScreens.lua
AltX.lua
Panel.BS.lua
Panel.Del.lua
Panel.Esc.lua
Panel.SpaceToSelect.lua
```
и вот такие плагины

```
align
autowrap
calc
colorer
editcase
editorcomp
filecase
incsrch
luafar
multiarc
netcfg
NetRocks
tmppanel
```
Есть что-то еще интреснее?

**Comment by Golyshkin** [comment]
@shmuz я глянул на https://github.com/shmuz/luafar2m, ну что сказать, там явно помойка из макросов и плагинов, чтобы начать этим пользоваться, надо, как минимум, написать для них ReadMe.txt

**Comment by shmuz** [comment]
> там явно помойка из макросов и плагинов

Со стороны может показаться помойкой, но это как раз тот набор плагинов и макросов, которым я постоянно пользуюсь.
За исключением папки `Macros/reserve`, но и там все макросы отлажены для far2m.

В отношении README согласен, неплохо было бы, но это немалая работа для такого количества макросов.
По макросам: у части из них есть вводный комментарий, иногда содержащий ссылку (URL) на обсуждение данного макроса в форуме Фар3.

Что касается плагинов, то там почти у всех есть HLF-файлы. Если открыть такой файл в редакторе far2m и нажать F1, то откроется справка в привычном формате помощи фара.
Некоторые из этих плагинов также имеют свои ветки обсуждения на форуме Фар3, например LF Search, LF History, Polygon.

**Comment by Golyshkin** [comment]
> Что касается плагинов, то там почти у всех есть HLF-файлы.

Это все не то, для каждого рабочего макроса или плагина ДОЛЖЕН быть описательный файл Readme.md/Readme.txt который хорошо описывает его функциональность! Без этого никто просто так ставить их не будет!

**Comment by shmuz** [comment]
Ну хорошо, дело ваше.
В таком случае мне не очень понятно, какой смысл для вас использования именно far2m, ведь те простые макросы, которыми вы пользуетесь, легко делаются и для far2l (а скорее всего уже существуют).

**Comment by Golyshkin** [comment]
Я начал пользовать FAR2M потому что FAR2L не читал нормально LUA файлы, а к тому моменту FAR2M уже мог.

**Comment by Zeroes1** [comment]
> Я начал пользовать FAR2M потому что FAR2L не читал нормально LUA файлы, а к тому моменту FAR2M уже мог.

FAR2L впринципе про LUA незнал и незнает.

**Comment by shmuz** [comment]
Far2l и сейчас не читает Lua-файлы. Однако те макросы, которыми вы пользуетесь, наверняка существуют в формате старого макроязыка (вот например https://github.com/elfmz/far2l/discussions/1146).

**Comment by Zeroes1** [comment]
@Golyshkin FAR2M нужен только тем кто не может жить без LUA, и стандартные макросы не могут обеспечить нужный функционал. Иначе лучше сидеть на FAR2L.

**Comment by Golyshkin** [comment]
@shmuz значит я не могу, т.к. часто делаю exchange LUA между FAR2M & WIN FAR :-) Мне очень нравится что они совместимы через LUA.

**Comment by shmuz** [comment]
@Golyshkin
Поймите меня правильно, я не предлагаю переходить на far2l. Наоборот, хотел чтобы вы воспользовались мощными и разнообразными утилитами, которые лежат на расстоянии одного клика мыши.

**Comment by Golyshkin** [comment]
@shmuz обязательно, только давайте начнем с описания для чего они нужны и какой функционал выполняют!? Иначе, как ими пользоваться?

**Comment by shmuz** [comment]
> давайте начнем с описания для чего они нужны и какой функционал выполняют

Я развиваю far2m **в одиночку**, и должен хорошо взвешивать, каким задачам дать больший приоритет. Имеются серьёзные покуда не решённые технические проблемы с одной стороны и нехватка документации с другой. Технические проблемы мне важнее.

Для сравнения: разработчик far2l получает еженедельно 5-10 пулл-реквестов, **включая добавления и правки документации**. Я получил за всё время разработки far2m не более 3 пулл-реквестов, ни один из которых не касался документации. Другими словами, приходится выбирать, на что тратить время.

Ну и добавлю, что документацию на luafar и luamacro (папка Manuals) я обновляю всегда, при любых изменениях.

**Comment by Golyshkin** [comment]
Хорошее дело делаете! Я бы даже помогал, но FULL TIME на работе. По поводу реквестов! Тут нужна правильная политика и реклама, вот например, я вообще случайно узнал про FAR2M, а вот если бы он назывался FAR2L+ и имел соотв. описание, то выскакивал бы гораздо чаще в запросах, т.к. базируется на том же сочетании букв и соотв. имел бы большее ко-во участников проекта! Тут есть много деталей, одному такой проект невытянуть по сравнению с FAR2L и будущее все-таки за интеграцию с ним ИМХО

**Comment by shmuz** [comment]
> Хорошее дело делаете!

Спасибо.
Я прекрасно понимаю, что "сражаться" с far2l не имеет смысла, т.к. он уже (заслуженно) занял эту нишу. Но я изначально и не ставил себе такую цель.

Пользуясь случаем, привожу [ссылку](https://github.com/shmuz/luafar2m/wiki), имеющую некоторое отношение к разговору о документации, на которую нет времени. Но нашёл время сделать несколько скриншотов.

**Comment by Golyshkin** [comment]
> Пользуясь случаем, привожу [ссылку](https://github.com/shmuz/luafar2m/wiki), имеющую некоторое отношение к разговору о документации, на которую нет времени. Но нашёл время сделать несколько скриншотов.

1. Да, еще бы пару строчек добавить и ссылку на репо где забрать
2. Было бы неплохо также включить в макросы на базе LUA
```
    AltScreens.lua
    AltX.lua
    Panel.BS.lua
    Panel.Del.lua
    Panel.Esc.lua
    Panel.SpaceToSelect.lua
```

**Comment by shmuz** [comment]
> Да, еще бы пару строчек добавить и ссылку на репо где забрать

Добавление краткого текста можно будет сделать (взять из шапок макросов или добавить из головы).
А ссылку я приводил выше, вы сказали что-то вроде того, что это помойка.

> Было бы неплохо также включить в макросы на базе LUA

Это можно будет сделать при случае.
