### ISSUE TITLE
Window title does not change immediately after changes are made in an "Interface settings" dialog window

### ISSUE THREAD

**Issue by ivanshatsky** [shmuz/far2m#52]
Что в целом в общем-то и ожидаемо.
Это я был автором коммита https://github.com/shmuz/far2m/commit/60e93e76e6aa37915801504e297cd437da763af0
После закрытия диалогового окна и срабатывания деструктора `~ConsoleTitle()` восстанавливается старое значение window title без учёта последних изменений.
Но что странно, в far2l видно, как сначала восстанавливается старое значение, а потом сразу меняется на новое.
А в far2m надо, чтобы сработало изменение window title, например после смены текущего каталога.
Такое чувство, что в far2l `SetFarTitle` дёргается кем-то ещё раз, а в far2m этого уже не происходит.
У вас есть идеи, из-за чего это происходит в far2l, и как это можно поправить в far2m?

**Comment by shmuz** [comment]
Это из-за тайм-аута, у меня уже пару недель руки чешутся его убрать.
https://github.com/shmuz/far2m/blob/65c6fdf322c5356d352b83c5ca61cff71348163b/far/src/console/constitle.cpp#L125

**Comment by shmuz** [comment]
Тайм-аут из этой функции убран, можно проверять.
У меня промежуточной перерисовки не видно, возможно потому, что машина локальная и быстрая.
