### ISSUE TITLE
Поведение Quick Search при нажатии Alt (Alt-Tab)

### ISSUE THREAD

**Issue by kos-v-kos** [shmuz/far2m#54]
Первое - при нажатии Alt-Tab для перехода в другое окно, в фаре выскакивает и остается висеть окошко "Quick Search" (если вернуться в фар и снова нажать Alt-Tab, окошко пропадает, т.е., я так понимаю, Quick Search срабатывает на нажатие Alt - логичнее было бы, если б срабатывал на отпускание)

Второе - если в текущей директории есть файл, начинающийся с "Б" (именно с большой "б"), то после нажатия Alt в выскакивающее "Quick Search" вставляется символ "<", и курсор перескакивает на этот файл на "Б":

![image](https://github.com/shmuz/far2m/assets/40456939/49333c66-ec9a-49c7-b425-c98f07db4b2d)

**Comment by shmuz** [comment]
Нужна дополнительная информация
- имя и версия операционной системы
- версия far2m (отображается в консоли, например "FAR2M, version 2.6.0-2024-02-21-73b3b78c-beta Linux x86_64")
- команда запуска far2m
- far2m сами собирали ли брали с PPA
- что выводит команда `lua:=far.AdvControl("ACTL_WINPORTBACKEND")`
- находясь в far2m, что выводят команды
`echo $XDG_SESSION_TYPE`
`echo $GDK_BACKEND`
`echo $DESKTOP_SESSION`
- какие макросы установлены
- каким сочетанием клавиш переключаете язык клавиатуры

**Comment by kos-v-kos** [comment]
блиин, это я тормоз - не проверил макросы. Я перетащил несколько макросов из виндового фара, и там есть файл AltSearch.lua , в котором вот такой макрос:
`Macro {
  description="Use Alt to toggle fast find mode";
  area="Shell";
  key="Alt";
  flags="NoSendKeysToPlugins";
  action=function()
    Keys("Alt<")
  end;
}
`

Он, как раз, эту "<" и вставляет.
Тогда вопрос - можно ли этот макрос адаптировать под Линух? В винде работает нормально, а в Линуксе - вот такое.

**Comment by shmuz** [comment]
Попробуйте снять отметку с указанной опции и нажать OK.
Если после этого будет всё нормально, сохраните конфигурацию (ShiftF9).

![image](https://github.com/shmuz/far2m/assets/344558/9ad3a4ee-24b1-4620-ac6a-68439793dea2)

**Comment by shmuz** [comment]
Я (с недавнего времени) использую в far2m следующий макрос. Пропробуйте, может быть он вас больше устроит, чем ваш нынешний.
```lua
Macro {
  description="Quick search";
  area="Shell"; key="/LAlt\\S/";
  action=function()
    local ch = akey(1):sub(-1)
    Keys("Alt*", ch)
  end;
}
```
