### ISSUE TITLE
проблема с прорисовкой результата поиска файлов

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#56]
проблема с прорисовкой результата поиска файлов
[рассинхронизация потоков поиска и отображения информации?]

как минимум после запроса на повышение прав
проверено на FAR2M 2.6.0-2024-03-07-3eaf5b3-beta Linux x86_64

авторизовались на Linux под ограниченным юзером
запустили Far2m
перешли в корень
зашли в \boot\

запустили поиск файлов *

какие то файлы появляются но попутно просит в фоне задать пароль для повышения прав

вводим в результате информация найденных файлов исчезает (но она есть там)

если стрелочки вверх вниз покрутить появляются найденные данные

**Comment by Zeroes1** [comment]
Тайкой же тикет для FAR2L https://github.com/elfmz/far2l/issues/2047

**Comment by shmuz** [comment]
Можно закрывать ли ещё что-то осталось?
