### ISSUE TITLE
Нет запроса на повышение прав если FAR2M запущен после FAR2L

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#57]
Найдена "некая" несовместимость FAR2M и FAR2L

запускаем FAR2M
пытаемся зайти в каталог \root
под ограниченной учётной записью
идёт запрос на повышение прав

запускаем FAR2L - тоже самое (из Far2m вышли)

запускаем
FAR2M и в ней ещё экземпляр FAR2M (возможно другой версии) запрос на повышение идёт опять
FAR2L и в ней ещё экземпляр FAR2L (возможно другой версии) запрос на повышение идёт опять

но если запустить FAR2L после FAR2M или наоборот FAR2M после FAR2L то запроса на повышение прав нет в обоих случаях
просто access denied и до свидания.

Эффект стабилен.
проверено на актуальных версиях на 07.03.2024
скомпиленные вручную/из PPA/ портативные

проверено при работе по SSH на ubuntu-23.10-live-server-amd64

**Comment by Zeroes1** [comment]
https://github.com/elfmz/far2l/issues/2048

**Comment by akruphi** [comment]
А может поступить радикальнее и явно смешивающиеся переменные окружения вроде `SUDO_ASKPASS` и `FARSETTINGS` в far2m переименовать, например в `FAR2M_SUDO_ASKPASS` и `FAR2M_SETTINGS`? Это немого усложнит для @shmuz синхронизацию кода, но зато не потребует внесения изменений в far2l и оставит наследственность для дочерних процессов.

**Comment by shmuz** [comment]
@akruphi 
Если мне кто-то доступно объяснит в чём смысл наследования именно этих переменных, буду благодарен.

**Comment by shmuz** [comment]
@akruphi 
`SUDO_ASKPASS` нельзя переименовывать, это имя не внутреннее фаровское. Если погуглить, сразу увидите.
