### ISSUE TITLE
проблемы с прорисовкой

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#58]
проблемы с прорисовкой

проверено на актуальном FAR'е 08.03.2024
и на самом старом что есть у меня от 19.12.2023

на FAR2L ситуация не воспроизводится

воспроизводится с дефолтными настройками
в частности ТОЧНО нужны
```
 ╔════════════ Настройка автозавершения ════════════╗
 ║ [x] Показывать список                            ║
 ║     [ ] Модальный режим                          ║
```

делаем тест:
в каталоге например \home\100

создаём подкаталоги (по F7) 1 и 10
далее 10 удаляем

тест1

жмём f7 поле названия жмём 1 (единицу)
должен появится DialogAutocompletion
с историей 1 и 10
выбираем 10 из списка и жмём Enter
создался каталог на активной 10, а на пассивной панели видна полоска
не исчезнет пока не рефрешним панель (например не нажмём Tab)

тест2
жмём f7 поле названия жмём 1 (единицу)
выбираем 1 + Enter
получаем сообщение о ошибке что каталог уже существует
сзади видна не прорисовка после отмены не прорисовка исчезает

100% воспроизводимость

https://github.com/shmuz/far2m/assets/11919060/2d3a138c-99b8-44b8-a4a2-da617be73253

тест по SSH на ubuntu-23.10-live-server-amd64

**Comment by shmuz** [comment]
Можно проверять.

**Comment by Zeroes1** [comment]
fixed. thanks
