### ISSUE TITLE
Error with -v option when no file found

### ISSUE THREAD

**Issue by sorcodiv** [shmuz/far2m#59]
Если запустить far2m с опцией открытия несуществующего файла, то получаю зацикливающуюся ошибку:
`./far2m -v nofile.txt`
> /test/far2m/_build/install/Plugins/luafar/luamacro/plug/luamacro.far-plug-wide:
...2m/_build/install/Plugins/luafar/luamacro/plug/utils.lua:1140: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
[C]: in function 'pairs'
...2m/_build/install/Plugins/luafar/luamacro/plug/utils.lua:1140: in function <...2m/_build/install/Plugins/luafar/luamacro/plug/utils.lua:1131>

Если запускаю с выключенными макросами - то получаю ожидаемое сообщение:
`./far2m -m -v nofile.txt`
> No such file or directory (2)
Cannot open the file

`FAR2M, version 2.6.0-2024-03-12-5caa2a2-beta Linux x86_64`

**Comment by shmuz** [comment]
Спасибо!  Тот же баг и в Фар3. Сейчас попробую починить.

**Comment by shmuz** [comment]
Можно проверять.

**Comment by sorcodiv** [comment]
Проблема решена, спасибо
