### ISSUE TITLE
Восстановление позиции на панелях при старте FAR2M

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#60]
Добавить возможность восстановления позиционирования на файловых элементах на панелях при запуске FAR

[это было не реализовано в FAR2 в FAR3 уже работает]

по ShiftF9 или при автосохранении данные фиксируются уже в значениях:

Panel/Right.CurFile
Panel/Left.CurFile

пока обошёл через макрос
_macroinit.lua

```
-- Set Global var area
_G.MyVars = _G.MyVars or {}

-- Restore current file on panels (if before saved)

if not (MyVars.Set2Files) then

local RFile = Far.GetConfig("Panel/Right.CurFile")
local LFile = Far.GetConfig("Panel/Left.CurFile")

if APanel.Left then
 Panel.SetPos(0, LFile)
 Panel.SetPos(1, RFile)
else
 Panel.SetPos(0, RFile)
 Panel.SetPos(1, LFile)
end

MyVars.Set2Files = true
end
```

**Comment by shmuz** [comment]
Проверяйте (только сначала отключите свой макрос).

**Comment by Zeroes1** [comment]
Вроде всё Ok. big thanks!
