### ISSUE TITLE
FS path  with spaces look incorrect

### ISSUE THREAD

**Issue by Golyshkin** [shmuz/far2m#62]
For long paths with spaces FAR2M displays as following

`/home/ADMSK/adgolys1/./Exponaut\ -\ An\ example\ 2d\ platformer\ \(see\ how\ it\ works\) `

![image](https://github.com/shmuz/far2m/assets/772340/a1900d42-7565-484c-b896-20493a4eeee3)

it's causing find problems in most GUI file managers (console works as expected). 

![image](https://github.com/shmuz/far2m/assets/772340/08602d9e-cfbb-4cfb-a6ed-fce22052fb73)

Does way to disable adding slash for such paths? I didn't find any related settings in `lm:farconfig`

**Comment by shmuz** [comment]
> FS path with spaces look incorrect

It depends on what is considered correct. This backslash escaping is handy for shell commands.

> Does way to disable adding slash for such paths?

`Ctrl+Alt+Ins` puts the full path in the clipboard "as is".

**Comment by shmuz** [comment]
Please describe your use case.
If there is no suitable command out-of-the box then a simple macro can solve the problem.
I could help if I knew exactly what you're trying to do.

**Comment by shmuz** [comment]
Thank you for the description.
But I want to see the **whole** use case, the **exact** steps you do after the path is in the command line.
In other words, I want to be able to reproduce your **whole** sequence.
I want to perform the test under Ubuntu 22.04.

**Comment by shmuz** [comment]
If all you need from Far is copying the full path to the clipboard then why `Ctrl+Alt+Ins` is worse than `Ctrl+] Ctrl+Enter` ?

**Comment by Golyshkin** [comment]
> If all you need from Far is copying the full path to the clipboard then why `Ctrl+Alt+Ins` is worse than `Ctrl+] Ctrl+Enter` ?

Yes, it's OK and could be used, but not documented and wide distributed as `Ctrl+]` & `Ctrl+Enter`, so I would like to request to have a special configuration to switch off auto slashing the paths contain spaces...

**Comment by Golyshkin** [comment]
> Thank you for the description. But I want to see the **whole** use case, the **exact** steps you do after the path is in the command line. In other words, I want to be able to reproduce your **whole** sequence. I want to perform the test under Ubuntu 22.04.

Just copy produced by FAR2M path with escapes to any Ubuntu file manager (use Ctrl+L for Ubuntu Files) and see the result described above (first issue description)

**Comment by shmuz** [comment]
> Yes, it's OK and could be used, but not documented

It is documented, see the screenshot from help:
![image](https://github.com/shmuz/far2m/assets/344558/528334d3-88ad-47cd-8685-0f9a96394390)

> Just copy produced by FAR2M path with escapes to any Ubuntu file manager

Yes, that is expected if those file managers expect a "pure" file name.
However, since there is a simple way to achieve this, I don't see the need to add a new option.
I respect your opinion, but I'm very reluctant to add new options.
