### ISSUE TITLE
Усовершенствовать mf.eval

### ISSUE THREAD

**Issue by johnd0e** [shmuz/far2m#64]
mf.eval исторически служит для разного, но лично меня интересуют лишь то что она делает в при Mode=2, т.е. исполнение макросов по имени клавиши и (опционально) названию макрообласти.

Например, один из распространённых паттернов такой:
```lua
if mf.eval("Esc",2)==-2 then Keys"Esc" end
```

Другое важное для меня место применения, это скрипт [MacroEx](https://forum.farmanager.com/viewtopic.php?f=15&t=8764), и там могут встречаться названия клавиш, с которыми eval сейчас работает неверно, см. [0002899: eval(S,2) и макросы, содержащие слэш в имени клавиши](https://bugs.farmanager.com/view.php?id=2899)

Предлагаю тут обсудить, стоит ли как-то усовершенствовать mf.eval, или реализовать требуемую функциональность отдельно.

**Comment by shmuz** [comment]
Если вы полагаете, что отдельная функция предпочтительней, дайте описание такой функции (примерно как описываются функции в мануале).

**Comment by johnd0e** [comment]
У меня пока нет окончательного решения.
Отдельную узкоспециализированную функцию очень просто было бы сделать.
Но может быть стоит предусмотреть какие-то флаги, например если нет макроса, то послать обычное нажатие клавиши.
(пока склоняюсь к тому что не надо).

Другое применение - что если требуется не выполнить макрос, а только узнать существует ли он, и/или выполняются ли все необходимые условия.
И не только узнать, но и получить его.
В случае если найдено несколько "конфликтующих" макросов, то хотелось бы получить все.

Если же макрос уже получен, то вероятно есть смысл выполнить его "напрямую" - например через action, или лучше иметь специальный метод в метатаблице, который сам позаботится о том чтобы правильно передать нужные аргументы.

**Comment by shmuz** [comment]
Тикету [0002899](https://bugs.farmanager.com/view.php?id=2899), на который вы ссылаетесь, уже более 9 лет.
Причина его нереализации мне видится в размытости и неконкретности формулировок задачи.
Я предлагаю, раз не получается сформулировать идеальное "общее" решение, давайте сформулируем **задачу-минимум**, как можно более конкретно и однозначно. Тогда можно будет её реализовать (и закрыть данный тикет).

**Comment by johnd0e** [comment]
> Причина его нереализации мне видится в размытости и неконкретности формулировок задачи.

В каком смысле "размытости"? Изначально вопрос очень конкретно стоял, и даже исправление там же приведено.


> Я предлагаю, раз не получается сформулировать идеальное "общее" решение[...]

Общее решение должно отталкиваться от конкретных практических задач.
И задачи эти есть, исходя из них я и описал примерно пожелания, но чтобы сформулировать финальную спецификацию, надо в эти задачи полностью погрузиться, и написать код, решающих их исходя из новой спецификации.

Рано или поздно я к этому вернусь, а тикет нужен для того чтобы подытожить текущее соображения, потому что через время уже может быть сложно всё вспомнить.

> давайте сформулируем **задачу-минимум**,

Минимум в этом смысле это исправить "eval", чтобы была возможность исполнить макросы, содержащие слэш в середине. На данный момент мне видится наиболее однозначным например такой вариант: синтаксис "Area/Key" остаётся, но Area может быть пустой строкой, и это будет равнозначно тому что Area не указан.
Например `mf.eval("/Ctrl/:Double",2)` будет означать поиск макроса с именем "Ctrl/:Double" в текущей макрообласти и в Common.

Если данная задача будет решена так, то я открою новый Issue - навроде "Чем заменить eval(xxx, 2)".

**Comment by shmuz** [comment]
В `luamacro\api.lua` замените функцию `Eval_GetData` на нижеприведенную, проверьте, и скажите, решает ли это изменение "задачу-минимум".
```lua
local function Eval_GetData (str) -- Получение данных макроса для Eval(S,2).
  local Mode = far.MacroGetArea()
  local UseCommon = false
  str = str:match("^%s*(.-)%s*$")

  local strArea,strKey = str:match("^(.-)/(.+)$")
  if strArea then
    if strArea ~= "." then -- вариант "./Key" не подразумевает поиск в макрообласти Common
      local SpecifiedMode = utils.GetAreaCode(strArea)
      if SpecifiedMode then
        Mode = SpecifiedMode
      else
        strKey = str
        UseCommon = true
      end
    end
  else
    strKey = str
    UseCommon = true
  end

  return Mode, strKey, UseCommon
end
```

**Comment by johnd0e** [comment]
Мою задачу решает, но не учитывает гипотетическую возможность имён вида "editor/xyz" (именно ради этого я предлагал начинать со слэша.)
Впрочем, реальной практической потребности в подобных именах у меня пока ни разу не возникало, поэтому на ваше усмотрение.
В конце концов, можно всегда исправить, когда появится реальная потребность.

**Comment by shmuz** [comment]
> не учитывает гипотетическую возможность имён вида "editor/xyz" (именно ради этого я предлагал начинать со слэша.)

А мне кажется, учитывает.

**Comment by johnd0e** [comment]
Я имею ввиду что например макрос с `area="common", key="editor/xyz"` при попытке исполнить его через `mf.eval("editor/xyz",2)` разделиться на:
- Area: "Editor"
- Key: "xyz"

Тогда как хочется иметь возможность исполнить его как
- Area: "Current" или "Common"
- Key: "editor/xyz"

**Comment by shmuz** [comment]
> Тогда как хочется иметь возможность исполнить его как [....]

Так вы же сами предложили в подобных случаях начинать со слеша.
Если указать `mf.eval("/editor/xyz",2)` то будет как раз то что надо.

**Comment by johnd0e** [comment]
В том и дело, что со слешем не работает.

`lua:eval("Ctrl/:Double",2)` запускает
`lua:eval("/Ctrl/:Double",2)` не запускает

**Comment by shmuz** [comment]
Тогда пробуем это:
```lua
local function Eval_GetData (str) -- Получение данных макроса для Eval(S,2).
  local Mode = far.MacroGetArea()
  local UseCommon = false
  str = str:match("^%s*(.-)%s*$")

  local slash, strArea, strKey = str:match("^(/?)(.-)/(.+)$")
  if slash == '/' then
    strKey = str:sub(2)
    UseCommon = true
  elseif strArea then
    if strArea ~= "." then -- вариант "./Key" не подразумевает поиск в макрообласти Common
      local SpecifiedMode = utils.GetAreaCode(strArea)
      if SpecifiedMode then
        Mode = SpecifiedMode
      else
        strKey = str
        UseCommon = true
      end
    end
  else
    strKey = str
    UseCommon = true
  end

  return Mode, strKey, UseCommon
end
```

**Comment by johnd0e** [comment]
`area="Editor"; key="editor/xyz xyz";`

- [x] `lua:eval("editor/xyz",2)` вызывает "xyz", что и требуется
- [ ] `lua:eval("/editor/xyz",2)` не вызывает ничего

Мой вариант:
```lua
local function Eval_GetData (str) -- Получение данных макроса для Eval(S,2).
  local Mode = far.MacroGetArea()
  local UseCommon = false
  str = str:match("^%s*(.-)%s*$")

  local strArea, strKey = str:match("^(.-)/(.+)$")
  if strArea then
    if strArea == "" then -- вариант "/Key" нужен в случае если сам Key содержит "/" в середине
      UseCommon = true
    elseif strArea ~= "." then -- вариант "./Key" не подразумевает поиск в макрообласти Common
      local SpecifiedMode = utils.GetAreaCode(strArea)
      if SpecifiedMode then
        Mode = SpecifiedMode
      else
        strKey = str
        UseCommon = true
      end
    end
  else
    strKey = str
    UseCommon = true
  end
  return Mode, strKey, UseCommon
end
```

**Comment by shmuz** [comment]
> - [ ] `lua:eval("/editor/xyz",2)` не вызывает ничего

У меня работает согласно документации:
если есть существует макрос в текущей (или Common) области, назначенный на ключ `editor/xyz`, то он вызывается.

**Comment by johnd0e** [comment]
Видимо я вчера перемудрил с проверкой.

**Comment by shmuz** [comment]
Поскольку "задача-минимум" реализована, закрываю.
Сегодня сделаю коммит и в Far3.

**Comment by johnd0e** [comment]
Спасибо!
