### ISSUE TITLE
MacroBrowser - происходит сброс режима автофильтрации

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#68]
Если был включен режим автофильтрации по CtrlAltF, воспользовались модальным редактором и вернулись в интерфейс 
MacroBrowser - активированный режим автофильтрации исчезает.

в FAR3 он остаётся, можно сделать чтобы не исчезал?

**Comment by shmuz** [comment]
> в FAR3 он остаётся, можно сделать чтобы не исчезал?

Странно, но у меня он и в Far3 исчезает. Far3.0.6333 x64.

**Comment by Zeroes1** [comment]
Оказалось что это MenuAutoFilter.lua от John Doe восстанавливает (как и при вызове Mbrowsera сразу включает), ну OK, можно ли тогда сделать малой кровью восстановление самим макробраузером? вроде бы логичное поведение?

**Comment by shmuz** [comment]
> можно ли тогда сделать малой кровью восстановление самим макробраузером?

Боюсь, что малой кровью не получится.
В Far3 меню были переработаны и сделаны разновидностью диалога (билд 2897, затем полгода разгребания багов).
Диалоги (и меню после билда 2897 в Far3) предоставляют плагинам и макросам возможность внедриться в диалоговую процедуру и делать там вещи наподобие того, что в пакете от John Doe.
В far2 / far2l / far2m такой возможности нет.
Переделку, наподобие Far3.0.2897, делать пока не собираюсь. Но подумаю о других путях.

**Comment by shmuz** [comment]
Пробуйте.

**Comment by Zeroes1** [comment]
Работает, спасибо! :)
