### ISSUE TITLE
New FAR2M icon is ugly!

### ISSUE THREAD

**Issue by Golyshkin** [shmuz/far2m#69]
Asking to one more review the new updated FAR2M icon showed below

![image](https://github.com/shmuz/far2m/assets/772340/345afec9-5d92-4df0-a397-44f3ca154e19)

since looks very ugly, distract attention and annoys!

**Comment by shmuz** [comment]
The new icons were kindly submitted by a user.
far2m **should** have icons different from far2l ones.
If you can create and submit a better icon, please do and then I will ask users on the Telegram which one is better.

**Comment by Golyshkin** [comment]
Please take a look! All of them much better than current one :-)/

![far2m-1](https://github.com/shmuz/far2m/assets/772340/6c01a229-e8c8-40a8-b370-c390e8d49e9a)
![far2m-2](https://github.com/shmuz/far2m/assets/772340/92b26172-c0f3-4238-809a-6e910b2f5d33)
![far2m-3](https://github.com/shmuz/far2m/assets/772340/a142cb4d-f706-468b-ba3c-11ca5088d2b0)
![far2m-4](https://github.com/shmuz/far2m/assets/772340/698fb3fb-17b9-4917-b049-91ce61b861c2)
![far2m-5](https://github.com/shmuz/far2m/assets/772340/2318c511-0f1a-46b2-ba2c-9f64685f1847)

**Comment by shmuz** [comment]
1. Icons 3, 4 and 5 are virtually indistinguishable from the Far2l icon, so they cannot be used.
2. Better or worse is subjective. People may have different opinions.
3. When I have time I will make a poll on far2l Telegram channel to compare the current icon and your icons 1 and 2.

**Comment by shmuz** [comment]
Here are the poll results:
![image](https://github.com/shmuz/far2m/assets/344558/ec00eef0-a08b-469b-9380-9e76607bfa26)

**Comment by Golyshkin** [comment]
Кошмар

**Comment by shmuz** [comment]
По общению с пользователями far2m я понял, что большинство из них (я в том числе) имеют также и установленный far2l. Для таких пользователей иконки этих двух приложений должны заметно отличаться. Микроскопическое отличие не годится.
