### ISSUE TITLE
[Wish] Поведение Up/Down в Menu

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#70]
сейчас в Far2l/Far2m в Menu / MainMenu/ UserMenu
Если зажали Up/Down то курсор по достижению первого/последнего элемента в списке "прыгает" на последний/на первый
элемент и погнали дальше...

в FAR3 видимо когда то поменяли этот эффект и происходит остановка на первом/последнем элементе
и чтобы мы прыгнули на первый/последний элемент надо отпустить и ещё раз нажать Up/Down

в FAR3 поведение не зря так сделано
пример: зажали клавишу Down в большом списке меню чтобы достичь элемента около конца, но не раcсчитали и перепрыгнули
в начало. В FAR3 такое не произойдёт.

Как то играет в этом деле  флаг VMENU_WRAPMODE? или меняли поведение при нём:
Идею предложил автор ConEmu 13 лет назад
https://forum.farmanager.com/viewtopic.php?t=6563

> Есть встречное предложение. Немного переделать поведение этого "wrap".
> Когда зажата кнопка Up (Down) то курсор пробежав до самого верха (низа) должен остановиться. Но, если на самой верхней (нижней) строке еще раз нажать кнопку Up (Down) - курсор должен таки перепрыгнуть в другой конец списка и опять побежать.

**Comment by Zeroes1** [comment]
Есть подозрения что в tty отличить нажатие и удержание от последовательных нажатий вроде бы совсем нереально/проблематично...

**Comment by akruphi** [comment]
Реализовано в https://github.com/elfmz/far2l/commit/05783a23af1ecc2de2898cbe59f5b0c745ef8736

**Comment by shmuz** [comment]
> Реализовано в https://github.com/elfmz/far2l/commit/05783a23af1ecc2de2898cbe59f5b0c745ef8736

И перетащено в far2m.

**Comment by shmuz** [comment]
> В TTY по SSH у меня заработало как надо.

У меня по-прежнему не работает.
