### ISSUE TITLE
Build FAIL based on 7b45f2 commit

### ISSUE THREAD

**Issue by Golyshkin** [shmuz/far2m#73]
Build based on latest commit ```d0be818a16bf545c606ec89d7c81e906fd7b45f2``` is failed with error

```
[ 46%] Linking CXX executable ../install/Plugins/NetRocks/plug/NetRocks-FTP.broker
/usr/bin/ld: CMakeFiles/NetRocks-FTP.dir/src/Protocol/FTP/FTPConnection.cpp.o: in function `OpenSSLContext::OpenSSLContext(StringConfig const&)':
FTPConnection.cpp:(.text._ZN14OpenSSLContextC2ERK12StringConfig+0xe8): undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: CMakeFiles/NetRocks-FTP.dir/src/Protocol/FTP/FTPConnection.cpp.o: in function `TLSTransport::GetPeerFingerprint[abi:cxx11]()':
FTPConnection.cpp:(.text._ZN12TLSTransport18GetPeerFingerprintB5cxx11Ev+0x48): undefined reference to `SSL_get1_peer_certificate'
collect2: error: ld returned 1 exit status
make[2]: *** [NetRocks/CMakeFiles/NetRocks-FTP.dir/build.make:196: install/Plugins/NetRocks/plug/NetRocks-FTP.broker] Error 1
make[1]: *** [CMakeFiles/Makefile2:1738: NetRocks/CMakeFiles/NetRocks-FTP.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by shmuz** [comment]
Странно...
- на гитхабе автоматическая сборка собралась
- у меня на Mint 21.3 собралось
- у меня на Ubuntu 22.04 собралось
- изменений в NetRocks в последние полмесяца не было

Попробуйте сделать `make clean && make` из папки `_build`

**Comment by Golyshkin** [comment]
Нет, не помогает... Раньше все работало ОК! Думал сначала что проблема в `make -j4`, но на одном потоке тоже самое
```
[ 92%] Linking CXX executable ../install/Plugins/NetRocks/plug/NetRocks-FTP.broker
/usr/bin/ld: CMakeFiles/NetRocks-FTP.dir/src/Protocol/FTP/FTPConnection.cpp.o: in function `OpenSSLContext::OpenSSLContext(StringConfig const&)':
FTPConnection.cpp:(.text._ZN14OpenSSLContextC2ERK12StringConfig+0xe8): undefined reference to `SSL_CTX_ctrl'
/usr/bin/ld: CMakeFiles/NetRocks-FTP.dir/src/Protocol/FTP/FTPConnection.cpp.o: in function `TLSTransport::GetPeerFingerprint[abi:cxx11]()':
FTPConnection.cpp:(.text._ZN12TLSTransport18GetPeerFingerprintB5cxx11Ev+0x48): undefined reference to `SSL_get1_peer_certificate'
collect2: error: ld returned 1 exit status
make[2]: *** [NetRocks/CMakeFiles/NetRocks-FTP.dir/build.make:196: install/Plugins/NetRocks/plug/NetRocks-FTP.broker] Error 1
make[1]: *** [CMakeFiles/Makefile2:1738: NetRocks/CMakeFiles/NetRocks-FTP.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
```

**Comment by Golyshkin** [comment]
Сильно не стал думать на какой комит делать HARD RESET, взял вот этот

```6447b8093ffb6449726d7e515aa8d0b8dafe7877```

Все собралось без проблем...

```
[100%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpExecute.cpp.o
[100%] Built target multiarc
[100%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpGetLinkTarget.cpp.o
[100%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Protocol/SplitLocationSpecification.cpp.o
[100%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Protocol/Protocol.cpp.o
[100%] Linking CXX shared module ../install/Plugins/NetRocks/plug/NetRocks.far-plug-wide
[100%] Built target NetRocks
```

Ищите проблему в новом засабмиченном коде...

**Comment by shmuz** [comment]
> Ищите проблему в новом засабмиченном коде...

Плагины, входящие в состав far2l, я не модифицирую, а только переношу изменения в far2m, если в этих плагинах что-то меняется. Бывают изредка исключения, но не с NetRocks.

Функции, которые линкер не может найти, входят в состав библиотеки `libssl`.
Попробуйтен переустановить её:
```
sudo apt remove libssl-dev`
sudo apt install libssl-dev`
```
После этого сделайте полный ребилд.

Неисправность пока проявляется только на вашей системе, иначе бы я получил дополнительные багрепорты, а в far2l была бы куча репортов.

**Comment by shmuz** [comment]
Кроме автоматических сборок на Github, происходят также автоматические ежедневные сборки здесь: https://launchpad.net/~far2l-team/+archive/ubuntu/lua , причём сразу для нескольких версий Ubuntu. Если бы была проблема, она бы и там вылезла.

**Comment by Golyshkin** [comment]
Пересобрал на новой хостовой машине...

**Comment by shmuz** [comment]
Тогда, с вашего позволения, закрываю :)
Если будут новые данные, можно будет переоткрыть.

**Comment by Golyshkin** [comment]
Да, вроде собралось на другой машине.
