### ISSUE TITLE
Strange behavior for NumEnter

### ISSUE THREAD

**Issue by Zeroes1** [shmuz/far2m#74]
при наличии макроса на NumEnter= Enter [неважно в Scripts или Internal] при обязательном DisableOutput 
возникают проблемы, например делаем команду dir в ком строке  запуск делаем через NumEnter

жмём потом CtrlO
видим 2 проблемы

1) вместо dir
dirdir
2) отрисовка кусков панелей которых не должно быть

![image](https://github.com/user-attachments/assets/911b4631-26ba-492d-b55e-a6c57e5fc92b)

проблема из кода Far2L 
https://github.com/elfmz/far2l/issues/2410

воспроизводимость проблемы 100%

**Comment by Zeroes1** [comment]
теперь всё гуд. Я так понимаю исправление годится и для Far2l?

**Comment by shmuz** [comment]
По существу исправления оно годится, по форме может не совпадать (в far2m используется препроцессорный макрос SCOPED_ACTION, которого на данный момент нет в far2l).
