### ISSUE TITLE
Дублирование "многострочных" записей в истории диалогов

### ISSUE THREAD

**Issue by johnd0e** [shmuz/far2m#75]
Если в поле ввода содержится символ "\n" то при занесении в историю этот символ заменяется на "\r".

При этом возможно дублирование записей, судя по всему ошибка в проверке уникальности записи.

1. Воспроизвести можно например в диалоге F7.
2. Создаём директорию с именем "1\n2\n\3", где вместо "\n" - [символ с кодом `10` (`0x0A`)](https://ss64.com/ascii.html).
   (Чтобы ввести его в поле ввода надо использовать последовательность <kbd>Ctrl+Q</kbd>, <kbd>Ctrl+J</kbd>).
3. Повторно открываем диалог, где видим что наш символ заменён на символ с кодом `13`.
4. Исправляем на символ с кодом `10`, и нажимаем <kbd>Enter</kbd>
5. Открываем диалог снова, смотрим в историю, и видим там 2 идентичные записи.
6. Можно повторить.

**Comment by shmuz** [comment]
Можно проверять когда будет следующий PPA.
